custom_components/localtuya/cover.py
custom_components/localtuya/light.py
custom_components/localtuya/switch.py

This adds support for `unique_id` and `available`. Benefits are:
* A config entry will be created so that entity name and friendly name can be changed from UI
* The device will appear as `unavailable` if an update fails, e.g. due to network problems, which makes it easier to spot if a device is not working

Add support for unique_id and available

---

custom_components/localtuya/config_flow.py
custom_components/localtuya/translations/en.json

Still prefer to keep '(YAML)' suffix for Integrations imported from YAML, for the moment.

Rospogrigio friendly name

---

custom_components/localtuya/config_flow.py
custom_components/localtuya/const.py
custom_components/localtuya/translations/en.json

This brings generic support for options to all platforms. It basically triggers the same steps as when adding a new device (with the configured entities). A few things to note:
* Not supported for YAML configs. This is basically because the YAML config overwrites what's stored in the config entry every time Home Assistant is restarted, so this kinda loses the point.
* It is not possible to change device id or id for any of the platforms. The ids are used to derive unique identifiers and allowing to change them will seriously mess things up. You basically create new devices and entities when doing so.
* Changes are not reflected until Home Assistant is restarted for now. I will change this, but it requires some refactoring.
* DPS values supported by a device is cached in the config entry, …

Add support for config flow option

---

custom_components/localtuya/__init__.py
custom_components/localtuya/cover.py
custom_components/localtuya/light.py
custom_components/localtuya/pytuya/__init__.py
custom_components/localtuya/switch.py

In pytuya, renamed set_dpsUsed into add_dps_to_request , which accepts single dps indexes instead of a list.
Used it when setting up entities.

Handling of dps to request in the payload

---

custom_components/localtuya/const.py
custom_components/localtuya/sensor.py
custom_components/localtuya/translations/en.json

This PR adds a generic `sensor` platform that can use any DP as state. It supports unit of measurement, device class and value scaling. A caveat regarding scaling is that it's an integer only as the schema validation seems to limit float to [0, 1[. I have asked if it's possible to use larger floating point values on discord, just waiting for response. If it's not possible I guess we can have one divisor and one multiplier instead

Add generic sensor platform

---

custom_components/localtuya/__init__.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/pytuya/__init__.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

Moved TuyaCache to __init__.py, and renamed to TuyaDevice. Removed TuyaCache from all platforms.
In pytuya, renamed TuyaDevice to TuyaInterface.
First half of PR #32.

Unified TuyaCache, now renamed to TuyaDevice

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

The purpose of this refactor is to remove circular dependencies between the platforms and main module, as this causes problems when implementing #40.

Extract shared code into a common module

---

custom_components/localtuya/binary_sensor.py
custom_components/localtuya/const.py
custom_components/localtuya/translations/en.json

Allows creation of a `binary_sensor` based on arbitrary DP. Strings can be provided for "on" and "off" and are case-insensitive.

Add generic binary_sensor platform

---

custom_components/localtuya/__init__.py
custom_components/localtuya/binary_sensor.py
custom_components/localtuya/common.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/const.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

Basically #40. Instead of setting up devices via platforms (e.g. `switch: ... platform: localtuya`), we now set up it up via the component (`localtuya:`).
One "device" object (pytuya) is also set up per device instead of one per entity.

Move to component from platform schemas

---

custom_components/localtuya/__init__.py
custom_components/localtuya/binary_sensor.py
custom_components/localtuya/common.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

This is the one that needs some serious testing.

Get status once per device instead of per platform

---

custom_components/localtuya/common.py
custom_components/localtuya/switch.py

This should fix the bug reported on the community forums:
```python
...
File “/config/custom_components/localtuya/switch.py”, line 220, in device_state_attributes
self.dps(self._config[CONF_CURRENT_CONSUMPTION]) / 10
TypeError: unsupported operand type(s) for /: ‘NoneType’ and ‘int’
...
```

Fix missing attributes bug

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py
custom_components/localtuya/pytuya/__init__.py

Optimizing the set_dps calls.
With previous implementation, `TuyaDevice.set_dps()` just clears the cached status, resulting in a delay before having the status updated.
Actually, the call returns a json with the new status of the changed DPs, such as:
`{'devId': 'xxxxxx', 'dps': {'7': False}}`
This PR introduces (and fixes) the decryption of the response of the `TuyaInterface.set_dps()` call, and uses the returned JSON to update the TuyaDevice cached status.
TODO ( @postlund please help):
once the cached status is updated, we probably need to call the `status_updated()` method for each entity involved, right? Which is the best way to do this? I don't know whether it's better to dispatch a signal, or to call the methods directly, or whatever.
BTW, I think the involved entity should be just …

Updating the status of TuyaDevice using the response of the set_dps() call

---

custom_components/localtuya/binary_sensor.py
custom_components/localtuya/common.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

This adds all platform specific DPS to requests by inspecting the config flow. So it will work with all platforms with no additional changes now or in the future. I did some refactoring to make this happen, by pulling `async_setup_entry` back to `__init__.py` as its basically the same for all platforms.

Add platform specific DPS to requests

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py
custom_components/localtuya/light.py
custom_components/localtuya/translations/en.json

This makes it possible to specify DP for brightness and color temperature via YAML config and config flow. Should be tested before merging.

Add color temp and brightness config to light

---

custom_components/localtuya/binary_sensor.py
custom_components/localtuya/common.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/pytuya/__init__.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

Renames `set_dps` to `set_dp` and introduces `set_dps` which can set multiple datapoints at once (needed for RGB support).

Fix naming of set_dps in pytuya

---

custom_components/localtuya/__init__.py
custom_components/localtuya/const.py
custom_components/localtuya/light.py
custom_components/localtuya/translations/en.json

Home Assistant uses brightness range 0-255 whilst Tuya somewhere around
29-1092. This commit maps brightness between these two ranges.

Re-map light brightness range

---

custom_components/localtuya/pytuya/__init__.py

This handles responses without a return code and also fixes support for
unencrypted clients. Made a few tweaks to debug logs as well.

Fix bugs in pytuya

---

README.md
custom_components/localtuya/common.py
custom_components/localtuya/const.py
custom_components/localtuya/light.py
custom_components/localtuya/pytuya/__init__.py
custom_components/localtuya/translations/en.json

This PR contains:
- RGB Support
- Brightness consistency between color and white modes
- Optional color temperature range
- Use of single call to update multiple data points, reducing latency
I didn't add an option to configure the color_temp upper value as for all the bulbs i have, they are always in sync with the brightness max values.
Configuration is explained in the README
```yaml
- platform: light
friendly_name: Device Light
id: 4 # Usually 1 or 20
color_mode: 21 # Optional, usually 2 or 21, default: "none"
brightness: 22 # Optional, usually 3 or 22, default: "none"
color_temp: 23 # Optional, usually 4 or 23, default: "none"
color: 24 # Optional, usually 5 (RGB_HSV) or 24(HSV), default: "none"
brightness_lower: 29 # Optional, usually 0 or 29, default: 29
brightness_upper: 1000 # …
```

Add support of RGB lights

---

custom_components/localtuya/sensor.py

Removed defalut scale factor of 1.0. 
The code is already applying the scale only if defined. Having a default value prevents using String sensor as it tries to apply the scale.
Should fix [issue 135](https://github.com/rospogrigio/localtuya/issues/135).

Fix default scale factor preventing use of String sensors

---

custom_components/localtuya/light.py

When a scene is created using the HA scene editor, it stores the complete status of the light.
When the scene is applied, HA scene this complete status.
In my previous PR, I forced the color to hs [0, 0] to be sure that the color picker return to white when we use color_temp
With that, the scene editor will now store this white value. If we detect this value, we force ignore the color and only set the white related settings.

Fix white only scene on RGBW lights

---

custom_components/localtuya/const.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/translations/en.json

This updates the fan controller to be more dynamic on which dp's it uses.
Fan speeds can 1,2,3,4 or low,medium,mid,high,auto.  Fans with more
than 3 speeds is not supported by Home Assistant.
Variable speed fans are not supported at this time.

Fan controller updates

---

custom_components/localtuya/binary_sensor.py
custom_components/localtuya/common.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/light.py
custom_components/localtuya/pytuya/__init__.py
custom_components/localtuya/sensor.py
custom_components/localtuya/switch.py

I have tried adding device id to all log points now. Not sure if it's the best way, but it's a try. This PR is however very important as many issues are hard to debug without it.
Fixes #95

Add contextual logging where applicable

---

README.md
custom_components/localtuya/const.py
custom_components/localtuya/light.py
custom_components/localtuya/translations/en.json

This PR is adding basic supports of scenes for tuya lights.
```yaml
- platform: light
friendly_name: Device Light
id: 4 # Usually 1 or 20
...
scene: 25 # Optional, usually 6 (RGB_HSV) or 25 (HSV), default: "none"
music_mode: False # Optional, some use internal mic, others, phone mic. Only internal mic is supported, default: "False"
```
We cannot get the scenes from the lights.
So this PR uses default scenes stored in the app for both RGB and HSV light bulbs.
If a scene is modified in the app, it appears as custom and but could not be use in a home assistant scene.
The music mode is also added but should only works with specific hardware that have a mic.

Scene support for lights.

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/const.py
custom_components/localtuya/cover.py

Store the device product key when creating a config entry. It will be automatically updated by the discovery in case it's missing in an existing config entry (e.g. prior to this PR or for YAML config). When available, it  be presented as the device model in the device registry.
I'm preparing a bit for the future "device database"-thing I've been talking about. It's a bit in the future, but I might as well do small tidbits when I get a feeling.

Store product key in config entry

---

custom_components/localtuya/pytuya/__init__.py

Seen as:
AttributeError: module 'logging' has no attribute 'EXCEPTION'

Fix broken exception logging

---

custom_components/localtuya/light.py

Fix also unwanted DP request that can generate unneeded log entry in DEBUG mode.

Use color picker white point to switch to white mode.

---

custom_components/localtuya/cover.py

This was due to wrong initialization values for _timer_start and _previous_state, should be fixed now.

Fix for issue #186 (covers start as offline)

---

custom_components/localtuya/config_flow.py

Forgot to add an await to the close method in pytuya when validating the
device. This results in the connection never being closed after adding a
device, giving "connection resets" until the connection fails, the
device or Home Assistant is restarted.

Fix improper closing in config flow

---

.gitignore
custom_components/localtuya/common.py
custom_components/localtuya/pytuya/__init__.py

This PR reduced the heartbeat interval to 10 seconds. Traffic is insignificant but seems to stabilize the connection between the integration and the devices.
Tried different values and 10 seconds is the largest which keep everything stable.

Reduce heartbeat interval.

---

custom_components/localtuya/light.py

This PR is re-using the white color in HS to switch from color to white in scenes for devices without color_temp.
It also fixing the requesting of color_mode for devices that only support brightness like dimmers.

Manage white and color scenes for light without color_temp

---

custom_components/localtuya/light.py

I noticed that, when using localtuya, changing the light from one state to another wasn't quite smooth. The light seemed to "turn off" and then go to the new state. For example, changing a light from red to green would make the light flash to being off, which was very unpleasant to the eyes.
I had a look in the code for localtuya and I found out that adding a simple `if`-statement in the `async_turn_on` function fixed this behavior.

Fix light state change when already on

---

custom_components/localtuya/__init__.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/discovery.py
custom_components/localtuya/translations/en.json

This is not what I should be working on, but I had most of the code sitting on a branch so I decided to finish it.
New  entities can be added via + button under Integrations (like when adding a new device, but select an existing device instead) and entities can be removed from Options.

Support adding and removing entities to devices

---

custom_components/localtuya/light.py
requirements_test.txt

I create a bunch of scenes with different kind of device configuration:
- RGB + CCT
- RGB + W
- RGB
- CCT
- W dimmer
Found a case that needs this fix 😄

Fix one more HA scene problem

---

custom_components/localtuya/pytuya/__init__.py

As we have devices that can be physically off and on like bulbs, this PR is changing the timeout log to a debug one. 
It keeps dumping the stack of any other exception.

Use debug message for timeout.

---

custom_components/localtuya/cover.py

Fixed close button disabled with 'none' positioning mode: if positioning is not used, `current_cover_position` method shall return None.

Fixed close button disabled with 'none' positioning mode

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py

This mimics the re-connect loop previosuly present, but in a simpler
form. Every 60 seconds, a new connection attempt is made as well as
initially when a device is set up.
I will add this an option, enabled by default so we can still support devices that sleep. But I want to get this out for testing.

Make connection retries every minute

---

custom_components/localtuya/fan.py

The Asakuki diffuser has its speed setting under the 103 DPS and uses "big" for its high setting.

Include "big" high fan setting

---

custom_components/localtuya/cover.py

This PR comes to fix 2 things in the cover integration:
- The timed mode should report the opened/closed state
- Fix the state inference
According to the [docs](https://developers.home-assistant.io/docs/core/entity/cover/) and the [code](https://github.com/home-assistant/core/blob/2e029458332c34b440a5c0118baa98f91f74f051/homeassistant/components/cover/__init__.py#L208-L220) the `is_open` attirube doesn't even exist. And the `is_closed` attribute should report `True` if the cover is fully closed, `False` if the cover is fully open and `None` otherwise (cover is somewhere in a middle position)

[covers] bug: state is not reported properly

---

custom_components/localtuya/light.py

If `light.turn_on` is invoked with `brightness: 128, color_temp: 500` for a bulb that supports mired range 154..370 in value range 1..255 the calculated color temperature will be negative.  When the bulb receives the command it will turn on, but will fail processing the `4: -153` command to set color_temp and will not send a response packet.
At this point `light.toggle` will have no effect because Home Assistant was never told the bulb was turned on, so the same erroneous turn-on command will be re-sent.
Fix this by clamping the sent color temperature to the allowed range.
This PR also includes a patch that solves the same problem as #577 but does so by using the core function rather than fixing the local reimplementation.

Fix color temperature to use correct conversion and clamp to allowed range

---

custom_components/localtuya/climate.py

BHT-002 thermostat DP 4 set the heating mode (auto or manual). The accepted values are strings "0" for auto mode and "1" for manual mode.
This commit add an entry "1/0" to support this behaviour.
Solve issue #799

Add "1/0" entry for HVAC_MODE_SETS

---

custom_components/localtuya/number.py

Relates to issues [929](https://github.com/rospogrigio/localtuya/issues/929), [939](https://github.com/rospogrigio/localtuya/issues/939) & [941](https://github.com/rospogrigio/localtuya/issues/941)
I do not have any suitable tuya devices in use to test against this number entity however the warning in logs "LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity] is now gone
https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

Refactor number entity overrides

---

README.md
custom_components/localtuya/common.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/const.py
custom_components/localtuya/number.py
custom_components/localtuya/select.py
custom_components/localtuya/switch.py
custom_components/localtuya/translations/en.json

Disables RESET functionality unless RESET DPIDs are specified in the device config. 
Hopefully fixes issues #1019 #1015 
For all those requiring RESET (generally for plugs with power monitoring), try 18,19,20 if your device isn't responding.
Have done brief regression test on local system. If others could assist with testing this change to confirm the issue has been correctly identified, that would be appreciated.

Implementing safe default for devices not requiring RESET/Passive functionality - Fix for bug in 4.1.0

---

custom_components/localtuya/common.py
custom_components/localtuya/config_flow.py

Regression introduced in 33e0033b0a95003252779262e58a719a902c4d1e - accidentally refactored int to str
Fixes https://github.com/rospogrigio/localtuya/issues/1258
Fixes https://github.com/rospogrigio/localtuya/issues/1248
Supercedes #1251 (Partially)
Error unloading entry localtuya for localtuya
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
result = await component.async_unload_entry(hass, self)
File "/config/custom_components/localtuya/init.py", line 311, in async_unload_entry
await device.close()
File "/config/custom_components/localtuya/common.py", line 308, in close
await self._connect_task
File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
and …

Force to int to avoid  TypeError: '>' not supported between instances of 'str' and 'int' after editing entity.

---

custom_components/localtuya/discovery.py

👋 I've recently taken over maintainership of the [robovac integration](https://github.com/codefoodpixels/robovac) and have added autodiscovery to keep the IP addresses up to date. Someone mentioned that they were having issues with both the robovac and localtuya integrations running at the same time, and I believe that adding this to both of our integrations should resolve the issue.

Allow port reuse so that other integrations can read the same port

---

custom_components/localtuya/__init__.py
custom_components/localtuya/cloud_api.py

Original Issue: https://github.com/rospogrigio/localtuya/issues/1328   
Restarting HomeAssistant without an external internet connection fails initialization when API is set in config. Tries to get access token and has an uncontrolled crash.    
**Note:** The `else` in `__init.py` is because `tuya_api.async_get_devices_list()` **also** causes a crash without an internet connection.
This also fixes if there's a non-**ok** response from the cloud. This might not be beneficial in all cases; Example: having invalid credentials, it might be better to have the crash so the user is aware of the issue. If that is desired I propose having a custom exception instead of waiting until `async_get_devices_list` fails.

Fixes #1328

---

custom_components/localtuya/climate.py
custom_components/localtuya/cover.py
custom_components/localtuya/fan.py
custom_components/localtuya/vacuum.py
hacs.json

Replaced SUPPORT_* with enums, set minimum HA version in HACS configuration to 2024.1.0
Issue #1610 
- Replaced SUPPORT_* with enums
- Set minimum HA version in HACS configuration to 2024.1.0

Fix #1610 - Replaced SUPPORT_* with enums

---

custom_components/localtuya/__init__.py

Hola! 👋 
Based on https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/ 
It seems it is possible to replace `async_forward_entry_setup` that requires a call for each supported platform with `async_forward_entry_setups` instead, which accepts multiple platforms and it should be more efficient, removing the need to also use `asyncio.gather`.
Just a small PR. Let me know if I'm missing something.

Replace deprecated HA async entry setup call with suggestion.
