custom_components/localtuya/light.py
custom_components/localtuya/manifest.json
custom_components/localtuya/pytuya/__init__.py

Updated light.py to support lights including capturing supported features for dimmable and colour temp. Tested _only_ with dimmable since I don't have a colour temp light.

Updated to support lights with dimmable and colour_temp settings

---

custom_components/localtuya/fan.py
custom_components/localtuya/pytuya/__init__.py

Added fan support.   for me it is a Technical Pro FXA16 WIFI Enabled 16 Inch Standing Fan With Oscillating Feature.
https://www.amazon.com/gp/product/B07RM6XQ4L/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
Added fan.py
Updated pytuya/__init__.py with FanDevice class

Add fan support

---

custom_components/localtuya/fan.py

@rospogrigio I think you managed to miss most of the stuff in the fan PR when fixing the conflict. I re-applied that PR and verified by adding both a single and double gang socket with success. So this should be fine.

Fix fan platform after merge

---

custom_components/localtuya/config_flow.py
custom_components/localtuya/pytuya/__init__.py

Pytuya 8.1.0, now provides the detect_available_dps method, which works both for type_0a and type_0d devices.
Introduced in config_flow validate_input method.

Autodetect available dps

---

custom_components/localtuya/__init__.py
custom_components/localtuya/switch.py

The `LocalTuyaEntity` contains common entity code and is also based on a config entry, which will allow us to adjust to changes options automatically. Only implemented for switch here, will do the other platforms separately. Please have a look at this @rospogrigio, it will save us a lot of code.

Extract common code

---

custom_components/localtuya/__init__.py
custom_components/localtuya/cover.py
custom_components/localtuya/switch.py

Applied #18 to cover platform too.
@postlund can you review this please? Code is getting sleeker and sleeker... 😄

LocaltuyaCover now inherits from LocalTuyaEntity

---

custom_components/localtuya/config_flow.py
custom_components/localtuya/discovery.py
custom_components/localtuya/translations/en.json

Devices are discovered during the first step and presented in a list. Let me know if it works!

Add device discovery to config flow

---

custom_components/localtuya/__init__.py

This makes changes under options apply without restart.

Reload integration if config entry changes

---

custom_components/localtuya/fan.py

This PR cleans up the `fan` platform and makes it inherit from `LocalTuyaEntity`. I had to pull in a copy of `TuyaCache` to be compatible with `LocalTuyaEntity`. The intention is to remove the cache class, but it's easier to do if we make all platforms work in the same way so we have a pattern. So pulling that class in is intentional and will be fixed soon.
NB: I don't have a fan so I can't verify if this works, but I hope it will. Current implementation on `masted` is broken in `turn_on` (due to old call to `turn_on` instead of `set_dps`), so it is probably a better change. Code has been statically verified with flake8 and pylint.

Make fan platform inherit from LocalTuyaEntity

---

custom_components/localtuya/light.py
custom_components/localtuya/switch.py

Migration of the last platform to `LocalTuyaEntity`. I have cleaned up and tried to fix a lot of errors, e.g. missing methods and spelling errors. I believe this should work at least better than before but I can't try it out as I don't have any light devices.

Make light entity inherit from LocalTuyaEntity

---

custom_components/localtuya/pytuya/__init__.py
requirements_test.txt
setup.cfg
tox.ini

This is the last part of the CI stuff. After this we check the code with pydocstyle, flake8, code spell and typing with mypy. We are also well prepared for tests.

Fix typing and spelling

---

custom_components/localtuya/discovery.py
custom_components/localtuya/manifest.json
custom_components/localtuya/pytuya/__init__.py
requirements_test.txt

An attempt to switch from `pycryptodome` to `cryptography`.

Switch to cryptograhy for crypto routines

---

custom_components/localtuya/__init__.py

Do not block event loop on updates

---

custom_components/localtuya/__init__.py
custom_components/localtuya/services.yaml

@rospogrigio Here's something to get going.

Add support for reloading from YAML

---

custom_components/localtuya/fan.py

Made a quick fix for `fan`. It annoyed the crap out of me that the file was dos encoded, so I changed that to Unix. That's why it looks like everything changed...

Convert fan platform to asyncio

---

custom_components/localtuya/config_flow.py
custom_components/localtuya/discovery.py
custom_components/localtuya/fan.py
custom_components/localtuya/translations/en.json

This one is for you @rospogrigio 😉

Improve discovery error output

---

custom_components/localtuya/__init__.py

Not sure how this happened, but a fix is needed.

Add missing variable to log point

---

custom_components/localtuya/discovery.py

Properly close discovery listeners

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py
custom_components/localtuya/services.yaml

I promised a while back to add a device that can change a datapoint, so here it is. Should be quite self explanatory I hope. Please git it a spin!
NB: This build upon the commits in #171 (passive device), so it must be merged before this PR.

Add localtuya.set_dp service

---

custom_components/localtuya/__init__.py
custom_components/localtuya/common.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/discovery.py
custom_components/localtuya/light.py
custom_components/localtuya/pytuya/__init__.py
pyproject.toml
requirements_test.txt
tox.ini

Pylint can find more stuff that flake8 does not, so it's useful run. I hardcoded the latest Home Assistant version as dependency for now.
@rospogrigio It would be great if you set up Dependabot for this project. That way we get dependency bumps automatically. I will add a config that auto-merges if tox passes. You can enable it from here:
https://dependabot.com/

Run pylint from tox

---

custom_components/localtuya/fan.py

This will allow to config BW-FUN3 diffuser
check this https://github.com/rospogrigio/localtuya/issues/172#issuecomment-753020257 for more details

allow set small / large values for low and high speed for fans

---

README.md

Thank you for this component. I went thru some of the sentences that were less clear to me and after working out how to set up my own devices I've updated some docs. 
* changed the grammar to use active voices (to sound like instructions)
* fixed some typos
* added links to HACS
* added links to contributor's github handles
* marked yaml so the syntax highlighting turns on in github

Grammar and spelling

---

custom_components/localtuya/common.py

I noticed that my switches are stuck in an `unavailable` state until I actually use them.
After long debugging, I realized that when the entity is created at boot time, it does not get an update from its device class. The logging clearly showed that the device was created and connected first, got the initial status of the device, and publish the event to the entities, but alas, the entities were not created yet... When they do get created, no one bothers to update their status until the physical device gets updated, rendering them stuck in an `unavailable` state.
I fixed it (and verified it on my HA instance) by making entities publish an event to the device letting them know they were created, so the device class can resend the status update event.

fix: major sync issue on mostly static entities caused by a race condition

---

custom_components/localtuya/__init__.py

Imported @sbneto suggestion, to optimize setup_entities by regrouping the platforms.

Optimized setup_entities by regrouping platforms

---

custom_components/localtuya/climate.py

This mode is required for the `Eurom LPL-15`

#711 Implemented m/p HVAC mode set

---

.github/workflows/tox.yaml
custom_components/localtuya/common.py
custom_components/localtuya/config_flow.py
custom_components/localtuya/pytuya/__init__.py
pylint.rc
tox.ini

Improved logging.
Introduced local_key update on device edit.
Fixed devices not reconnecting any more in certain cases.

Stability fixes

---

custom_components/localtuya/manifest.json
custom_components/localtuya/pytuya/__init__.py

Fixes #1406, #1417 and other potential duplicates.

Fix for socket.send() exceptions in the logs

---

custom_components/localtuya/__init__.py
custom_components/localtuya/vacuum.py

Deprecation fixes for  #1851, #1864, #1871, #1905, #1932, #1940, #1949.

Address HASS reported deprecations
